// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: StreamedFileHeaderEnvelope.proto

// Protobuf Java Version: 3.25.6
package proto.builtin;

public final class StreamedFileHeaderEnvelopeOuterClass {
  private StreamedFileHeaderEnvelopeOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface StreamedFileHeaderEnvelopeOrBuilder extends
      // @@protoc_insertion_point(interface_extends:StreamedFileHeaderEnvelope)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Set of FileDescriptorProtos which describe the type and its dependencies.
     * </pre>
     *
     * <code>.google.protobuf.FileDescriptorSet descriptorValue = 1;</code>
     * @return Whether the descriptorValue field is set.
     */
    boolean hasDescriptorValue();
    /**
     * <pre>
     * Set of FileDescriptorProtos which describe the type and its dependencies.
     * </pre>
     *
     * <code>.google.protobuf.FileDescriptorSet descriptorValue = 1;</code>
     * @return The descriptorValue.
     */
    com.google.protobuf.DescriptorProtos.FileDescriptorSet getDescriptorValue();
    /**
     * <pre>
     * Set of FileDescriptorProtos which describe the type and its dependencies.
     * </pre>
     *
     * <code>.google.protobuf.FileDescriptorSet descriptorValue = 1;</code>
     */
    com.google.protobuf.DescriptorProtos.FileDescriptorSetOrBuilder getDescriptorValueOrBuilder();

    /**
     * <pre>
     * The message and its type, encoded as an Any message.
     * </pre>
     *
     * <code>.google.protobuf.Any header = 2;</code>
     * @return Whether the header field is set.
     */
    boolean hasHeader();
    /**
     * <pre>
     * The message and its type, encoded as an Any message.
     * </pre>
     *
     * <code>.google.protobuf.Any header = 2;</code>
     * @return The header.
     */
    com.google.protobuf.Any getHeader();
    /**
     * <pre>
     * The message and its type, encoded as an Any message.
     * </pre>
     *
     * <code>.google.protobuf.Any header = 2;</code>
     */
    com.google.protobuf.AnyOrBuilder getHeaderOrBuilder();

    /**
     * <code>string headerMessageName = 3;</code>
     * @return The headerMessageName.
     */
    java.lang.String getHeaderMessageName();
    /**
     * <code>string headerMessageName = 3;</code>
     * @return The bytes for headerMessageName.
     */
    com.google.protobuf.ByteString
        getHeaderMessageNameBytes();

    /**
     * <code>string payloadMessageName = 4;</code>
     * @return The payloadMessageName.
     */
    java.lang.String getPayloadMessageName();
    /**
     * <code>string payloadMessageName = 4;</code>
     * @return The bytes for payloadMessageName.
     */
    com.google.protobuf.ByteString
        getPayloadMessageNameBytes();

    /**
     * <code>.google.protobuf.Timestamp writeTimeUtc = 5;</code>
     * @return Whether the writeTimeUtc field is set.
     */
    boolean hasWriteTimeUtc();
    /**
     * <code>.google.protobuf.Timestamp writeTimeUtc = 5;</code>
     * @return The writeTimeUtc.
     */
    com.google.protobuf.Timestamp getWriteTimeUtc();
    /**
     * <code>.google.protobuf.Timestamp writeTimeUtc = 5;</code>
     */
    com.google.protobuf.TimestampOrBuilder getWriteTimeUtcOrBuilder();
  }
  /**
   * Protobuf type {@code StreamedFileHeaderEnvelope}
   */
  public static final class StreamedFileHeaderEnvelope extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:StreamedFileHeaderEnvelope)
      StreamedFileHeaderEnvelopeOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use StreamedFileHeaderEnvelope.newBuilder() to construct.
    private StreamedFileHeaderEnvelope(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private StreamedFileHeaderEnvelope() {
      headerMessageName_ = "";
      payloadMessageName_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new StreamedFileHeaderEnvelope();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.builtin.StreamedFileHeaderEnvelopeOuterClass.internal_static_StreamedFileHeaderEnvelope_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.builtin.StreamedFileHeaderEnvelopeOuterClass.internal_static_StreamedFileHeaderEnvelope_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.builtin.StreamedFileHeaderEnvelopeOuterClass.StreamedFileHeaderEnvelope.class, proto.builtin.StreamedFileHeaderEnvelopeOuterClass.StreamedFileHeaderEnvelope.Builder.class);
    }

    private int bitField0_;
    public static final int DESCRIPTORVALUE_FIELD_NUMBER = 1;
    private com.google.protobuf.DescriptorProtos.FileDescriptorSet descriptorValue_;
    /**
     * <pre>
     * Set of FileDescriptorProtos which describe the type and its dependencies.
     * </pre>
     *
     * <code>.google.protobuf.FileDescriptorSet descriptorValue = 1;</code>
     * @return Whether the descriptorValue field is set.
     */
    @java.lang.Override
    public boolean hasDescriptorValue() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * Set of FileDescriptorProtos which describe the type and its dependencies.
     * </pre>
     *
     * <code>.google.protobuf.FileDescriptorSet descriptorValue = 1;</code>
     * @return The descriptorValue.
     */
    @java.lang.Override
    public com.google.protobuf.DescriptorProtos.FileDescriptorSet getDescriptorValue() {
      return descriptorValue_ == null ? com.google.protobuf.DescriptorProtos.FileDescriptorSet.getDefaultInstance() : descriptorValue_;
    }
    /**
     * <pre>
     * Set of FileDescriptorProtos which describe the type and its dependencies.
     * </pre>
     *
     * <code>.google.protobuf.FileDescriptorSet descriptorValue = 1;</code>
     */
    @java.lang.Override
    public com.google.protobuf.DescriptorProtos.FileDescriptorSetOrBuilder getDescriptorValueOrBuilder() {
      return descriptorValue_ == null ? com.google.protobuf.DescriptorProtos.FileDescriptorSet.getDefaultInstance() : descriptorValue_;
    }

    public static final int HEADER_FIELD_NUMBER = 2;
    private com.google.protobuf.Any header_;
    /**
     * <pre>
     * The message and its type, encoded as an Any message.
     * </pre>
     *
     * <code>.google.protobuf.Any header = 2;</code>
     * @return Whether the header field is set.
     */
    @java.lang.Override
    public boolean hasHeader() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * The message and its type, encoded as an Any message.
     * </pre>
     *
     * <code>.google.protobuf.Any header = 2;</code>
     * @return The header.
     */
    @java.lang.Override
    public com.google.protobuf.Any getHeader() {
      return header_ == null ? com.google.protobuf.Any.getDefaultInstance() : header_;
    }
    /**
     * <pre>
     * The message and its type, encoded as an Any message.
     * </pre>
     *
     * <code>.google.protobuf.Any header = 2;</code>
     */
    @java.lang.Override
    public com.google.protobuf.AnyOrBuilder getHeaderOrBuilder() {
      return header_ == null ? com.google.protobuf.Any.getDefaultInstance() : header_;
    }

    public static final int HEADERMESSAGENAME_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object headerMessageName_ = "";
    /**
     * <code>string headerMessageName = 3;</code>
     * @return The headerMessageName.
     */
    @java.lang.Override
    public java.lang.String getHeaderMessageName() {
      java.lang.Object ref = headerMessageName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        headerMessageName_ = s;
        return s;
      }
    }
    /**
     * <code>string headerMessageName = 3;</code>
     * @return The bytes for headerMessageName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getHeaderMessageNameBytes() {
      java.lang.Object ref = headerMessageName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        headerMessageName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PAYLOADMESSAGENAME_FIELD_NUMBER = 4;
    @SuppressWarnings("serial")
    private volatile java.lang.Object payloadMessageName_ = "";
    /**
     * <code>string payloadMessageName = 4;</code>
     * @return The payloadMessageName.
     */
    @java.lang.Override
    public java.lang.String getPayloadMessageName() {
      java.lang.Object ref = payloadMessageName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        payloadMessageName_ = s;
        return s;
      }
    }
    /**
     * <code>string payloadMessageName = 4;</code>
     * @return The bytes for payloadMessageName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getPayloadMessageNameBytes() {
      java.lang.Object ref = payloadMessageName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        payloadMessageName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int WRITETIMEUTC_FIELD_NUMBER = 5;
    private com.google.protobuf.Timestamp writeTimeUtc_;
    /**
     * <code>.google.protobuf.Timestamp writeTimeUtc = 5;</code>
     * @return Whether the writeTimeUtc field is set.
     */
    @java.lang.Override
    public boolean hasWriteTimeUtc() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>.google.protobuf.Timestamp writeTimeUtc = 5;</code>
     * @return The writeTimeUtc.
     */
    @java.lang.Override
    public com.google.protobuf.Timestamp getWriteTimeUtc() {
      return writeTimeUtc_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : writeTimeUtc_;
    }
    /**
     * <code>.google.protobuf.Timestamp writeTimeUtc = 5;</code>
     */
    @java.lang.Override
    public com.google.protobuf.TimestampOrBuilder getWriteTimeUtcOrBuilder() {
      return writeTimeUtc_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : writeTimeUtc_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (hasDescriptorValue()) {
        if (!getDescriptorValue().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(1, getDescriptorValue());
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeMessage(2, getHeader());
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(headerMessageName_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, headerMessageName_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(payloadMessageName_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, payloadMessageName_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeMessage(5, getWriteTimeUtc());
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getDescriptorValue());
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getHeader());
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(headerMessageName_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, headerMessageName_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(payloadMessageName_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, payloadMessageName_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, getWriteTimeUtc());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof proto.builtin.StreamedFileHeaderEnvelopeOuterClass.StreamedFileHeaderEnvelope)) {
        return super.equals(obj);
      }
      proto.builtin.StreamedFileHeaderEnvelopeOuterClass.StreamedFileHeaderEnvelope other = (proto.builtin.StreamedFileHeaderEnvelopeOuterClass.StreamedFileHeaderEnvelope) obj;

      if (hasDescriptorValue() != other.hasDescriptorValue()) return false;
      if (hasDescriptorValue()) {
        if (!getDescriptorValue()
            .equals(other.getDescriptorValue())) return false;
      }
      if (hasHeader() != other.hasHeader()) return false;
      if (hasHeader()) {
        if (!getHeader()
            .equals(other.getHeader())) return false;
      }
      if (!getHeaderMessageName()
          .equals(other.getHeaderMessageName())) return false;
      if (!getPayloadMessageName()
          .equals(other.getPayloadMessageName())) return false;
      if (hasWriteTimeUtc() != other.hasWriteTimeUtc()) return false;
      if (hasWriteTimeUtc()) {
        if (!getWriteTimeUtc()
            .equals(other.getWriteTimeUtc())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasDescriptorValue()) {
        hash = (37 * hash) + DESCRIPTORVALUE_FIELD_NUMBER;
        hash = (53 * hash) + getDescriptorValue().hashCode();
      }
      if (hasHeader()) {
        hash = (37 * hash) + HEADER_FIELD_NUMBER;
        hash = (53 * hash) + getHeader().hashCode();
      }
      hash = (37 * hash) + HEADERMESSAGENAME_FIELD_NUMBER;
      hash = (53 * hash) + getHeaderMessageName().hashCode();
      hash = (37 * hash) + PAYLOADMESSAGENAME_FIELD_NUMBER;
      hash = (53 * hash) + getPayloadMessageName().hashCode();
      if (hasWriteTimeUtc()) {
        hash = (37 * hash) + WRITETIMEUTC_FIELD_NUMBER;
        hash = (53 * hash) + getWriteTimeUtc().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static proto.builtin.StreamedFileHeaderEnvelopeOuterClass.StreamedFileHeaderEnvelope parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.builtin.StreamedFileHeaderEnvelopeOuterClass.StreamedFileHeaderEnvelope parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.builtin.StreamedFileHeaderEnvelopeOuterClass.StreamedFileHeaderEnvelope parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.builtin.StreamedFileHeaderEnvelopeOuterClass.StreamedFileHeaderEnvelope parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.builtin.StreamedFileHeaderEnvelopeOuterClass.StreamedFileHeaderEnvelope parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.builtin.StreamedFileHeaderEnvelopeOuterClass.StreamedFileHeaderEnvelope parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.builtin.StreamedFileHeaderEnvelopeOuterClass.StreamedFileHeaderEnvelope parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.builtin.StreamedFileHeaderEnvelopeOuterClass.StreamedFileHeaderEnvelope parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static proto.builtin.StreamedFileHeaderEnvelopeOuterClass.StreamedFileHeaderEnvelope parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static proto.builtin.StreamedFileHeaderEnvelopeOuterClass.StreamedFileHeaderEnvelope parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.builtin.StreamedFileHeaderEnvelopeOuterClass.StreamedFileHeaderEnvelope parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.builtin.StreamedFileHeaderEnvelopeOuterClass.StreamedFileHeaderEnvelope parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(proto.builtin.StreamedFileHeaderEnvelopeOuterClass.StreamedFileHeaderEnvelope prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code StreamedFileHeaderEnvelope}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:StreamedFileHeaderEnvelope)
        proto.builtin.StreamedFileHeaderEnvelopeOuterClass.StreamedFileHeaderEnvelopeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return proto.builtin.StreamedFileHeaderEnvelopeOuterClass.internal_static_StreamedFileHeaderEnvelope_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return proto.builtin.StreamedFileHeaderEnvelopeOuterClass.internal_static_StreamedFileHeaderEnvelope_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                proto.builtin.StreamedFileHeaderEnvelopeOuterClass.StreamedFileHeaderEnvelope.class, proto.builtin.StreamedFileHeaderEnvelopeOuterClass.StreamedFileHeaderEnvelope.Builder.class);
      }

      // Construct using proto.builtin.StreamedFileHeaderEnvelopeOuterClass.StreamedFileHeaderEnvelope.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getDescriptorValueFieldBuilder();
          getHeaderFieldBuilder();
          getWriteTimeUtcFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        descriptorValue_ = null;
        if (descriptorValueBuilder_ != null) {
          descriptorValueBuilder_.dispose();
          descriptorValueBuilder_ = null;
        }
        header_ = null;
        if (headerBuilder_ != null) {
          headerBuilder_.dispose();
          headerBuilder_ = null;
        }
        headerMessageName_ = "";
        payloadMessageName_ = "";
        writeTimeUtc_ = null;
        if (writeTimeUtcBuilder_ != null) {
          writeTimeUtcBuilder_.dispose();
          writeTimeUtcBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto.builtin.StreamedFileHeaderEnvelopeOuterClass.internal_static_StreamedFileHeaderEnvelope_descriptor;
      }

      @java.lang.Override
      public proto.builtin.StreamedFileHeaderEnvelopeOuterClass.StreamedFileHeaderEnvelope getDefaultInstanceForType() {
        return proto.builtin.StreamedFileHeaderEnvelopeOuterClass.StreamedFileHeaderEnvelope.getDefaultInstance();
      }

      @java.lang.Override
      public proto.builtin.StreamedFileHeaderEnvelopeOuterClass.StreamedFileHeaderEnvelope build() {
        proto.builtin.StreamedFileHeaderEnvelopeOuterClass.StreamedFileHeaderEnvelope result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public proto.builtin.StreamedFileHeaderEnvelopeOuterClass.StreamedFileHeaderEnvelope buildPartial() {
        proto.builtin.StreamedFileHeaderEnvelopeOuterClass.StreamedFileHeaderEnvelope result = new proto.builtin.StreamedFileHeaderEnvelopeOuterClass.StreamedFileHeaderEnvelope(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(proto.builtin.StreamedFileHeaderEnvelopeOuterClass.StreamedFileHeaderEnvelope result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.descriptorValue_ = descriptorValueBuilder_ == null
              ? descriptorValue_
              : descriptorValueBuilder_.build();
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.header_ = headerBuilder_ == null
              ? header_
              : headerBuilder_.build();
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.headerMessageName_ = headerMessageName_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.payloadMessageName_ = payloadMessageName_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.writeTimeUtc_ = writeTimeUtcBuilder_ == null
              ? writeTimeUtc_
              : writeTimeUtcBuilder_.build();
          to_bitField0_ |= 0x00000004;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof proto.builtin.StreamedFileHeaderEnvelopeOuterClass.StreamedFileHeaderEnvelope) {
          return mergeFrom((proto.builtin.StreamedFileHeaderEnvelopeOuterClass.StreamedFileHeaderEnvelope)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(proto.builtin.StreamedFileHeaderEnvelopeOuterClass.StreamedFileHeaderEnvelope other) {
        if (other == proto.builtin.StreamedFileHeaderEnvelopeOuterClass.StreamedFileHeaderEnvelope.getDefaultInstance()) return this;
        if (other.hasDescriptorValue()) {
          mergeDescriptorValue(other.getDescriptorValue());
        }
        if (other.hasHeader()) {
          mergeHeader(other.getHeader());
        }
        if (!other.getHeaderMessageName().isEmpty()) {
          headerMessageName_ = other.headerMessageName_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        if (!other.getPayloadMessageName().isEmpty()) {
          payloadMessageName_ = other.payloadMessageName_;
          bitField0_ |= 0x00000008;
          onChanged();
        }
        if (other.hasWriteTimeUtc()) {
          mergeWriteTimeUtc(other.getWriteTimeUtc());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (hasDescriptorValue()) {
          if (!getDescriptorValue().isInitialized()) {
            return false;
          }
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                input.readMessage(
                    getDescriptorValueFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                input.readMessage(
                    getHeaderFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                headerMessageName_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 34: {
                payloadMessageName_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              case 42: {
                input.readMessage(
                    getWriteTimeUtcFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000010;
                break;
              } // case 42
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.DescriptorProtos.FileDescriptorSet descriptorValue_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.DescriptorProtos.FileDescriptorSet, com.google.protobuf.DescriptorProtos.FileDescriptorSet.Builder, com.google.protobuf.DescriptorProtos.FileDescriptorSetOrBuilder> descriptorValueBuilder_;
      /**
       * <pre>
       * Set of FileDescriptorProtos which describe the type and its dependencies.
       * </pre>
       *
       * <code>.google.protobuf.FileDescriptorSet descriptorValue = 1;</code>
       * @return Whether the descriptorValue field is set.
       */
      public boolean hasDescriptorValue() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <pre>
       * Set of FileDescriptorProtos which describe the type and its dependencies.
       * </pre>
       *
       * <code>.google.protobuf.FileDescriptorSet descriptorValue = 1;</code>
       * @return The descriptorValue.
       */
      public com.google.protobuf.DescriptorProtos.FileDescriptorSet getDescriptorValue() {
        if (descriptorValueBuilder_ == null) {
          return descriptorValue_ == null ? com.google.protobuf.DescriptorProtos.FileDescriptorSet.getDefaultInstance() : descriptorValue_;
        } else {
          return descriptorValueBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * Set of FileDescriptorProtos which describe the type and its dependencies.
       * </pre>
       *
       * <code>.google.protobuf.FileDescriptorSet descriptorValue = 1;</code>
       */
      public Builder setDescriptorValue(com.google.protobuf.DescriptorProtos.FileDescriptorSet value) {
        if (descriptorValueBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          descriptorValue_ = value;
        } else {
          descriptorValueBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Set of FileDescriptorProtos which describe the type and its dependencies.
       * </pre>
       *
       * <code>.google.protobuf.FileDescriptorSet descriptorValue = 1;</code>
       */
      public Builder setDescriptorValue(
          com.google.protobuf.DescriptorProtos.FileDescriptorSet.Builder builderForValue) {
        if (descriptorValueBuilder_ == null) {
          descriptorValue_ = builderForValue.build();
        } else {
          descriptorValueBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Set of FileDescriptorProtos which describe the type and its dependencies.
       * </pre>
       *
       * <code>.google.protobuf.FileDescriptorSet descriptorValue = 1;</code>
       */
      public Builder mergeDescriptorValue(com.google.protobuf.DescriptorProtos.FileDescriptorSet value) {
        if (descriptorValueBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0) &&
            descriptorValue_ != null &&
            descriptorValue_ != com.google.protobuf.DescriptorProtos.FileDescriptorSet.getDefaultInstance()) {
            getDescriptorValueBuilder().mergeFrom(value);
          } else {
            descriptorValue_ = value;
          }
        } else {
          descriptorValueBuilder_.mergeFrom(value);
        }
        if (descriptorValue_ != null) {
          bitField0_ |= 0x00000001;
          onChanged();
        }
        return this;
      }
      /**
       * <pre>
       * Set of FileDescriptorProtos which describe the type and its dependencies.
       * </pre>
       *
       * <code>.google.protobuf.FileDescriptorSet descriptorValue = 1;</code>
       */
      public Builder clearDescriptorValue() {
        bitField0_ = (bitField0_ & ~0x00000001);
        descriptorValue_ = null;
        if (descriptorValueBuilder_ != null) {
          descriptorValueBuilder_.dispose();
          descriptorValueBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Set of FileDescriptorProtos which describe the type and its dependencies.
       * </pre>
       *
       * <code>.google.protobuf.FileDescriptorSet descriptorValue = 1;</code>
       */
      public com.google.protobuf.DescriptorProtos.FileDescriptorSet.Builder getDescriptorValueBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getDescriptorValueFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * Set of FileDescriptorProtos which describe the type and its dependencies.
       * </pre>
       *
       * <code>.google.protobuf.FileDescriptorSet descriptorValue = 1;</code>
       */
      public com.google.protobuf.DescriptorProtos.FileDescriptorSetOrBuilder getDescriptorValueOrBuilder() {
        if (descriptorValueBuilder_ != null) {
          return descriptorValueBuilder_.getMessageOrBuilder();
        } else {
          return descriptorValue_ == null ?
              com.google.protobuf.DescriptorProtos.FileDescriptorSet.getDefaultInstance() : descriptorValue_;
        }
      }
      /**
       * <pre>
       * Set of FileDescriptorProtos which describe the type and its dependencies.
       * </pre>
       *
       * <code>.google.protobuf.FileDescriptorSet descriptorValue = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.DescriptorProtos.FileDescriptorSet, com.google.protobuf.DescriptorProtos.FileDescriptorSet.Builder, com.google.protobuf.DescriptorProtos.FileDescriptorSetOrBuilder> 
          getDescriptorValueFieldBuilder() {
        if (descriptorValueBuilder_ == null) {
          descriptorValueBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.DescriptorProtos.FileDescriptorSet, com.google.protobuf.DescriptorProtos.FileDescriptorSet.Builder, com.google.protobuf.DescriptorProtos.FileDescriptorSetOrBuilder>(
                  getDescriptorValue(),
                  getParentForChildren(),
                  isClean());
          descriptorValue_ = null;
        }
        return descriptorValueBuilder_;
      }

      private com.google.protobuf.Any header_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> headerBuilder_;
      /**
       * <pre>
       * The message and its type, encoded as an Any message.
       * </pre>
       *
       * <code>.google.protobuf.Any header = 2;</code>
       * @return Whether the header field is set.
       */
      public boolean hasHeader() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <pre>
       * The message and its type, encoded as an Any message.
       * </pre>
       *
       * <code>.google.protobuf.Any header = 2;</code>
       * @return The header.
       */
      public com.google.protobuf.Any getHeader() {
        if (headerBuilder_ == null) {
          return header_ == null ? com.google.protobuf.Any.getDefaultInstance() : header_;
        } else {
          return headerBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * The message and its type, encoded as an Any message.
       * </pre>
       *
       * <code>.google.protobuf.Any header = 2;</code>
       */
      public Builder setHeader(com.google.protobuf.Any value) {
        if (headerBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          header_ = value;
        } else {
          headerBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The message and its type, encoded as an Any message.
       * </pre>
       *
       * <code>.google.protobuf.Any header = 2;</code>
       */
      public Builder setHeader(
          com.google.protobuf.Any.Builder builderForValue) {
        if (headerBuilder_ == null) {
          header_ = builderForValue.build();
        } else {
          headerBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The message and its type, encoded as an Any message.
       * </pre>
       *
       * <code>.google.protobuf.Any header = 2;</code>
       */
      public Builder mergeHeader(com.google.protobuf.Any value) {
        if (headerBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0) &&
            header_ != null &&
            header_ != com.google.protobuf.Any.getDefaultInstance()) {
            getHeaderBuilder().mergeFrom(value);
          } else {
            header_ = value;
          }
        } else {
          headerBuilder_.mergeFrom(value);
        }
        if (header_ != null) {
          bitField0_ |= 0x00000002;
          onChanged();
        }
        return this;
      }
      /**
       * <pre>
       * The message and its type, encoded as an Any message.
       * </pre>
       *
       * <code>.google.protobuf.Any header = 2;</code>
       */
      public Builder clearHeader() {
        bitField0_ = (bitField0_ & ~0x00000002);
        header_ = null;
        if (headerBuilder_ != null) {
          headerBuilder_.dispose();
          headerBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The message and its type, encoded as an Any message.
       * </pre>
       *
       * <code>.google.protobuf.Any header = 2;</code>
       */
      public com.google.protobuf.Any.Builder getHeaderBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getHeaderFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * The message and its type, encoded as an Any message.
       * </pre>
       *
       * <code>.google.protobuf.Any header = 2;</code>
       */
      public com.google.protobuf.AnyOrBuilder getHeaderOrBuilder() {
        if (headerBuilder_ != null) {
          return headerBuilder_.getMessageOrBuilder();
        } else {
          return header_ == null ?
              com.google.protobuf.Any.getDefaultInstance() : header_;
        }
      }
      /**
       * <pre>
       * The message and its type, encoded as an Any message.
       * </pre>
       *
       * <code>.google.protobuf.Any header = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> 
          getHeaderFieldBuilder() {
        if (headerBuilder_ == null) {
          headerBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder>(
                  getHeader(),
                  getParentForChildren(),
                  isClean());
          header_ = null;
        }
        return headerBuilder_;
      }

      private java.lang.Object headerMessageName_ = "";
      /**
       * <code>string headerMessageName = 3;</code>
       * @return The headerMessageName.
       */
      public java.lang.String getHeaderMessageName() {
        java.lang.Object ref = headerMessageName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          headerMessageName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string headerMessageName = 3;</code>
       * @return The bytes for headerMessageName.
       */
      public com.google.protobuf.ByteString
          getHeaderMessageNameBytes() {
        java.lang.Object ref = headerMessageName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          headerMessageName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string headerMessageName = 3;</code>
       * @param value The headerMessageName to set.
       * @return This builder for chaining.
       */
      public Builder setHeaderMessageName(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        headerMessageName_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>string headerMessageName = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearHeaderMessageName() {
        headerMessageName_ = getDefaultInstance().getHeaderMessageName();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>string headerMessageName = 3;</code>
       * @param value The bytes for headerMessageName to set.
       * @return This builder for chaining.
       */
      public Builder setHeaderMessageNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        headerMessageName_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      private java.lang.Object payloadMessageName_ = "";
      /**
       * <code>string payloadMessageName = 4;</code>
       * @return The payloadMessageName.
       */
      public java.lang.String getPayloadMessageName() {
        java.lang.Object ref = payloadMessageName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          payloadMessageName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string payloadMessageName = 4;</code>
       * @return The bytes for payloadMessageName.
       */
      public com.google.protobuf.ByteString
          getPayloadMessageNameBytes() {
        java.lang.Object ref = payloadMessageName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          payloadMessageName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string payloadMessageName = 4;</code>
       * @param value The payloadMessageName to set.
       * @return This builder for chaining.
       */
      public Builder setPayloadMessageName(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        payloadMessageName_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>string payloadMessageName = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearPayloadMessageName() {
        payloadMessageName_ = getDefaultInstance().getPayloadMessageName();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <code>string payloadMessageName = 4;</code>
       * @param value The bytes for payloadMessageName to set.
       * @return This builder for chaining.
       */
      public Builder setPayloadMessageNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        payloadMessageName_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }

      private com.google.protobuf.Timestamp writeTimeUtc_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> writeTimeUtcBuilder_;
      /**
       * <code>.google.protobuf.Timestamp writeTimeUtc = 5;</code>
       * @return Whether the writeTimeUtc field is set.
       */
      public boolean hasWriteTimeUtc() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <code>.google.protobuf.Timestamp writeTimeUtc = 5;</code>
       * @return The writeTimeUtc.
       */
      public com.google.protobuf.Timestamp getWriteTimeUtc() {
        if (writeTimeUtcBuilder_ == null) {
          return writeTimeUtc_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : writeTimeUtc_;
        } else {
          return writeTimeUtcBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.Timestamp writeTimeUtc = 5;</code>
       */
      public Builder setWriteTimeUtc(com.google.protobuf.Timestamp value) {
        if (writeTimeUtcBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          writeTimeUtc_ = value;
        } else {
          writeTimeUtcBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp writeTimeUtc = 5;</code>
       */
      public Builder setWriteTimeUtc(
          com.google.protobuf.Timestamp.Builder builderForValue) {
        if (writeTimeUtcBuilder_ == null) {
          writeTimeUtc_ = builderForValue.build();
        } else {
          writeTimeUtcBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp writeTimeUtc = 5;</code>
       */
      public Builder mergeWriteTimeUtc(com.google.protobuf.Timestamp value) {
        if (writeTimeUtcBuilder_ == null) {
          if (((bitField0_ & 0x00000010) != 0) &&
            writeTimeUtc_ != null &&
            writeTimeUtc_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
            getWriteTimeUtcBuilder().mergeFrom(value);
          } else {
            writeTimeUtc_ = value;
          }
        } else {
          writeTimeUtcBuilder_.mergeFrom(value);
        }
        if (writeTimeUtc_ != null) {
          bitField0_ |= 0x00000010;
          onChanged();
        }
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp writeTimeUtc = 5;</code>
       */
      public Builder clearWriteTimeUtc() {
        bitField0_ = (bitField0_ & ~0x00000010);
        writeTimeUtc_ = null;
        if (writeTimeUtcBuilder_ != null) {
          writeTimeUtcBuilder_.dispose();
          writeTimeUtcBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp writeTimeUtc = 5;</code>
       */
      public com.google.protobuf.Timestamp.Builder getWriteTimeUtcBuilder() {
        bitField0_ |= 0x00000010;
        onChanged();
        return getWriteTimeUtcFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.Timestamp writeTimeUtc = 5;</code>
       */
      public com.google.protobuf.TimestampOrBuilder getWriteTimeUtcOrBuilder() {
        if (writeTimeUtcBuilder_ != null) {
          return writeTimeUtcBuilder_.getMessageOrBuilder();
        } else {
          return writeTimeUtc_ == null ?
              com.google.protobuf.Timestamp.getDefaultInstance() : writeTimeUtc_;
        }
      }
      /**
       * <code>.google.protobuf.Timestamp writeTimeUtc = 5;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
          getWriteTimeUtcFieldBuilder() {
        if (writeTimeUtcBuilder_ == null) {
          writeTimeUtcBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                  getWriteTimeUtc(),
                  getParentForChildren(),
                  isClean());
          writeTimeUtc_ = null;
        }
        return writeTimeUtcBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:StreamedFileHeaderEnvelope)
    }

    // @@protoc_insertion_point(class_scope:StreamedFileHeaderEnvelope)
    private static final proto.builtin.StreamedFileHeaderEnvelopeOuterClass.StreamedFileHeaderEnvelope DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new proto.builtin.StreamedFileHeaderEnvelopeOuterClass.StreamedFileHeaderEnvelope();
    }

    public static proto.builtin.StreamedFileHeaderEnvelopeOuterClass.StreamedFileHeaderEnvelope getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<StreamedFileHeaderEnvelope>
        PARSER = new com.google.protobuf.AbstractParser<StreamedFileHeaderEnvelope>() {
      @java.lang.Override
      public StreamedFileHeaderEnvelope parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<StreamedFileHeaderEnvelope> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<StreamedFileHeaderEnvelope> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public proto.builtin.StreamedFileHeaderEnvelopeOuterClass.StreamedFileHeaderEnvelope getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_StreamedFileHeaderEnvelope_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_StreamedFileHeaderEnvelope_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n StreamedFileHeaderEnvelope.proto\032\031goog" +
      "le/protobuf/any.proto\032 google/protobuf/d" +
      "escriptor.proto\032\037google/protobuf/timesta" +
      "mp.proto\"\350\001\n\032StreamedFileHeaderEnvelope\022" +
      ";\n\017descriptorValue\030\001 \001(\0132\".google.protob" +
      "uf.FileDescriptorSet\022$\n\006header\030\002 \001(\0132\024.g" +
      "oogle.protobuf.Any\022\031\n\021headerMessageName\030" +
      "\003 \001(\t\022\032\n\022payloadMessageName\030\004 \001(\t\0220\n\014wri" +
      "teTimeUtc\030\005 \001(\0132\032.google.protobuf.Timest" +
      "ampB\017\n\rproto.builtinb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.AnyProto.getDescriptor(),
          com.google.protobuf.DescriptorProtos.getDescriptor(),
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_StreamedFileHeaderEnvelope_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_StreamedFileHeaderEnvelope_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_StreamedFileHeaderEnvelope_descriptor,
        new java.lang.String[] { "DescriptorValue", "Header", "HeaderMessageName", "PayloadMessageName", "WriteTimeUtc", });
    com.google.protobuf.AnyProto.getDescriptor();
    com.google.protobuf.DescriptorProtos.getDescriptor();
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
