# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PriceScenarios.proto
# Protobuf Python Version: 4.25.6
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14PriceScenarios.proto\"L\n\x0ePriceScenarios\x12\x11\n\tunderlyer\x18\x01 \x01(\t\x12\x18\n\x10instrumentSymbol\x18\x02 \x01(\t\x12\r\n\x05price\x18\x03 \x03(\x01\x42\x07\n\x05protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'PriceScenarios_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\005proto'
  _globals['_PRICESCENARIOS']._serialized_start=24
  _globals['_PRICESCENARIOS']._serialized_end=100
# @@protoc_insertion_point(module_scope)
